bugfix: Message is not comparable (ClassCastException)
Exception: Caused by: java.lang.ClassCastException: class io.github.stavshamir.springwolf.asyncapi.types.channel.operation.message.Message cannot be cast to class java.lang.Comparable (io.github.stavshamir.springwolf.asyncapi.types.channel.operation.message.Message is in unnamed module of loader 'app'; java.lang.Comparable is in module java.base of loader 'bootstrap')