test: improve testcontainer test stability
By default, a DockerComposeContainer copies the full gradle project directory into container.
When running tests, the `build/test-results/test/binary/output.bin` file is written, which can get large.
This file is not required for the tests and the test container default is overwritten to a single file (i.e. `.env`)

Original error messages:
org.testcontainers.containers.ContainerLaunchException: Container startup failed for image docker/compose
com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"unexpected EOF"}
java.io.IOException: Request to write '8192' bytes exceeds size in header of '2064381' bytes for entry